services:
  mongo:
    image: mongo:7
    container_name: mongo-gdrive
    restart: unless-stopped
    ports: ["27500:27017"]
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
    volumes:
      - mongo_data:/data/db
      - ./mongo-seed:/docker-entrypoint-initdb.d:ro

  redis:
    image: redis:7-alpine
    container_name: redis-gdrive
    restart: unless-stopped
    ports: ["6379:6379"]
    volumes:
      - redis_data:/data

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-ui
    restart: unless-stopped
    ports: ["8081:8081"]
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASS}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_USER}:${MONGO_PASS}@mongo:27017/
      ME_CONFIG_BASICAUTH_USERNAME: dev
      ME_CONFIG_BASICAUTH_PASSWORD: dev

  minio:
    image: minio/minio:latest
    container_name: minio-gdrive
    restart: unless-stopped
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_PASS}
    command: server /data --console-address ":9001"
    volumes:
      - ./minio-data:/data

volumes:
  mongo_data:
  redis_data:
  minio_data:
